# Generated by Django 4.1.3 on 2023-10-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0004_blog_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_content',
            name='anasayfa',
        ),
    ]
