# Generated by Django 4.1.3 on 2023-10-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0008_blog_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
