# Generated by Django 4.1.3 on 2023-10-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0009_alter_blog_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_content',
            name='slug',
        ),
    ]
