# Generated by Django 4.1.3 on 2023-10-10 19:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='icerik',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
