# Generated by Django 4.1.3 on 2023-10-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0002_alter_blog_content_icerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='anasayfa',
            field=models.BooleanField(default=True),
        ),
    ]
