# Generated by Django 4.1.3 on 2023-10-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0003_blog_content_anasayfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
