# Generated by Django 4.1.3 on 2023-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0007_remove_blog_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True),
        ),
    ]
