# Generated by Django 4.1.3 on 2023-10-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0013_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
