# Generated by Django 4.1.3 on 2023-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0017_blog_content_onerilenler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='kategori',
            field=models.CharField(choices=[('Yazılım', 'Yazılım'), ('Kitap', 'Kitap'), ('Film/Dizi', 'Film/Dizi'), ('Spor', 'Spor'), ('Oyun', 'Oyun'), ('Felsefe', 'Felsefe'), ('Psikoloji', 'Psikoloji'), ('Tarih', 'Tarih')], max_length=100),
        ),
    ]
