# Generated by Django 4.2.7 on 2023-11-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kesifblog', '0018_alter_blog_content_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='kategori_image',
            field=models.CharField(choices=[('Yazılım', 'Yazılım'), ('Kitap', 'Kitap'), ('Film/Dizi', 'Film/Dizi'), ('Spor', 'Spor'), ('Oyun', 'Oyun'), ('Felsefe', 'Felsefe'), ('Psikoloji', 'Psikoloji'), ('Tarih', 'Tarih')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
